name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Node.js with the specific version (v18.20.4)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      # Unset the CI environment variable to prevent warnings from causing build failures
      - run: |
          unset CI
          yarn
          yarn build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: filmo-55c78  # Your Firebase project ID
